/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.gs.vo;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2019-03-01 09:24:22
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class CheckBalanceVO extends SuperVO {
	private Integer voucher_no; //凭证号
	private String voucher_id;//凭证分录主键
	private String voucher_date;//凭证日期
	private String subject;//科目代码
	private String orgcode;//公司代码
	private String orgname;//公司名称
	private String bank_account;//银行账号
	private String bank_account_name;//账户名称
	private String bankname;//账号开户人 
	private String modifierid;//凭证制单人
	private String checker;//凭证复核人
	private String source;//凭证来源
	private String currency;//币种
	private UFDouble amount;//金额
	private String dirction;//借贷方向
	private String memo;//摘要
	private String other_name;//对方户名  用友系统中没有该字段
	private String fetch_flag;//资金是否取数  Y取数，N未取数
	private UFDateTime fetch_time;//资金取数时间
	private String confirm_flag;//对账标志 Y已对账，N是未对账，E对账失败
	private String pk_check_balance;
	private String attr_1;
	private String attr_2;
	private String attr_3;
	private String attr_4;
	private String attr_5;
	private UFDateTime ts;
	private Integer dr;

	public static final String FETCH_FLAG = "fetch_flag";
	public static final String ATTR_3 = "attr_3";
	public static final String BANK_ACCOUNT_NAME = "bank_account_name";
	public static final String VOUCHER_ID = "voucher_id";
	public static final String ORGNAME = "orgname";
	public static final String CONFIRM_FLAG = "confirm_flag";
	public static final String ATTR_5 = "attr_5";
	public static final String CHECKER = "checker";
	public static final String BANKNAME = "bankname";
	public static final String SOURCE = "source";
	public static final String OTHER_NAME = "other_name";
	public static final String FETCH_TIME = "fetch_time";
	public static final String VOUCHER_NO = "voucher_no";
	public static final String MODIFIERID = "modifierid";
	public static final String PK_CHECK_BALANCE = "pk_check_balance";
	public static final String SUBJECT = "subject";
	public static final String ORGCODE = "orgcode";
	public static final String CURRENCY = "currency";
	public static final String BANK_ACCOUNT = "bank_account";
	public static final String ATTR_4 = "attr_4";
	public static final String AMOUNT = "amount";
	public static final String MEMO = "memo";
	public static final String ATTR_1 = "attr_1";
	public static final String ATTR_2 = "attr_2";
	public static final String VOUCHER_DATE = "voucher_date";
	public static final String DIRCTION = "dirction";
			
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性fetch_flag的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getFetch_flag () {
		return fetch_flag;
	}   
	/**
	 * 属性fetch_flag的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newFetch_flag String
	 */
	public void setFetch_flag (String newFetch_flag ) {
	 	this.fetch_flag = newFetch_flag;
	} 	  
	/**
	 * 属性attr_3的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getAttr_3 () {
		return attr_3;
	}   
	/**
	 * 属性attr_3的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newAttr_3 String
	 */
	public void setAttr_3 (String newAttr_3 ) {
	 	this.attr_3 = newAttr_3;
	} 	  
	/**
	 * 属性bank_account_name的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getBank_account_name () {
		return bank_account_name;
	}   
	/**
	 * 属性bank_account_name的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newBank_account_name String
	 */
	public void setBank_account_name (String newBank_account_name ) {
	 	this.bank_account_name = newBank_account_name;
	} 	  
	/**
	 * 属性voucher_id的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getVoucher_id () {
		return voucher_id;
	}   
	/**
	 * 属性voucher_id的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newVoucher_id String
	 */
	public void setVoucher_id (String newVoucher_id ) {
	 	this.voucher_id = newVoucher_id;
	} 	  
	/**
	 * 属性orgname的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getOrgname () {
		return orgname;
	}   
	/**
	 * 属性orgname的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newOrgname String
	 */
	public void setOrgname (String newOrgname ) {
	 	this.orgname = newOrgname;
	} 	  
	/**
	 * 属性confirm_flag的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getConfirm_flag () {
		return confirm_flag;
	}   
	/**
	 * 属性confirm_flag的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newConfirm_flag String
	 */
	public void setConfirm_flag (String newConfirm_flag ) {
	 	this.confirm_flag = newConfirm_flag;
	} 	  
	/**
	 * 属性attr_5的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getAttr_5 () {
		return attr_5;
	}   
	/**
	 * 属性attr_5的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newAttr_5 String
	 */
	public void setAttr_5 (String newAttr_5 ) {
	 	this.attr_5 = newAttr_5;
	} 	  
	/**
	 * 属性checker的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getChecker () {
		return checker;
	}   
	/**
	 * 属性checker的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newChecker String
	 */
	public void setChecker (String newChecker ) {
	 	this.checker = newChecker;
	} 	  
	/**
	 * 属性bankname的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getBankname () {
		return bankname;
	}   
	/**
	 * 属性bankname的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newBankname String
	 */
	public void setBankname (String newBankname ) {
	 	this.bankname = newBankname;
	} 	  
	/**
	 * 属性source的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getSource () {
		return source;
	}   
	/**
	 * 属性source的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newSource String
	 */
	public void setSource (String newSource ) {
	 	this.source = newSource;
	} 	  
	/**
	 * 属性other_name的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getOther_name () {
		return other_name;
	}   
	/**
	 * 属性other_name的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newOther_name String
	 */
	public void setOther_name (String newOther_name ) {
	 	this.other_name = newOther_name;
	} 	  
	/**
	 * 属性fetch_time的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return UFDateTime
	 */
	public UFDateTime getFetch_time () {
		return fetch_time;
	}   
	/**
	 * 属性fetch_time的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newFetch_time UFDateTime
	 */
	public void setFetch_time (UFDateTime newFetch_time ) {
	 	this.fetch_time = newFetch_time;
	} 	  
	/**
	 * 属性voucher_no的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return UFDouble
	 */
	public Integer getVoucher_no () {
		return voucher_no;
	}   
	/**
	 * 属性voucher_no的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newVoucher_no UFDouble
	 */
	public void setVoucher_no (Integer newVoucher_no ) {
	 	this.voucher_no = newVoucher_no;
	} 	  
	/**
	 * 属性modifierid的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getModifierid () {
		return modifierid;
	}   
	/**
	 * 属性modifierid的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newModifierid String
	 */
	public void setModifierid (String newModifierid ) {
	 	this.modifierid = newModifierid;
	} 	  
	/**
	 * 属性pk_check_balance的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getPk_check_balance () {
		return pk_check_balance;
	}   
	/**
	 * 属性pk_check_balance的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newPk_check_balance String
	 */
	public void setPk_check_balance (String newPk_check_balance ) {
	 	this.pk_check_balance = newPk_check_balance;
	} 	  
	/**
	 * 属性subject的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getSubject () {
		return subject;
	}   
	/**
	 * 属性subject的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newSubject String
	 */
	public void setSubject (String newSubject ) {
	 	this.subject = newSubject;
	} 	  
	/**
	 * 属性orgcode的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getOrgcode () {
		return orgcode;
	}   
	/**
	 * 属性orgcode的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newOrgcode String
	 */
	public void setOrgcode (String newOrgcode ) {
	 	this.orgcode = newOrgcode;
	} 	  
	/**
	 * 属性currency的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getCurrency () {
		return currency;
	}   
	/**
	 * 属性currency的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newCurrency String
	 */
	public void setCurrency (String newCurrency ) {
	 	this.currency = newCurrency;
	} 	  
	/**
	 * 属性bank_account的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getBank_account () {
		return bank_account;
	}   
	/**
	 * 属性bank_account的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newBank_account String
	 */
	public void setBank_account (String newBank_account ) {
	 	this.bank_account = newBank_account;
	} 	  
	/**
	 * 属性attr_4的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getAttr_4 () {
		return attr_4;
	}   
	/**
	 * 属性attr_4的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newAttr_4 String
	 */
	public void setAttr_4 (String newAttr_4 ) {
	 	this.attr_4 = newAttr_4;
	} 	  
	/**
	 * 属性amount的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return UFDouble
	 */
	public UFDouble getAmount () {
		return amount;
	}   
	/**
	 * 属性amount的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newAmount UFDouble
	 */
	public void setAmount (UFDouble newAmount ) {
	 	this.amount = newAmount;
	} 	  
	/**
	 * 属性memo的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getMemo () {
		return memo;
	}   
	/**
	 * 属性memo的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newMemo String
	 */
	public void setMemo (String newMemo ) {
	 	this.memo = newMemo;
	} 	  
	/**
	 * 属性attr_1的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getAttr_1 () {
		return attr_1;
	}   
	/**
	 * 属性attr_1的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newAttr_1 String
	 */
	public void setAttr_1 (String newAttr_1 ) {
	 	this.attr_1 = newAttr_1;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性attr_2的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getAttr_2 () {
		return attr_2;
	}   
	/**
	 * 属性attr_2的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newAttr_2 String
	 */
	public void setAttr_2 (String newAttr_2 ) {
	 	this.attr_2 = newAttr_2;
	} 	  
	/**
	 * 属性voucher_date的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return String
	 */
	public String getVoucher_date () {
		return voucher_date;
	}   
	/**
	 * 属性voucher_date的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newVoucher_date String
	 */
	public void setVoucher_date (String newVoucher_date ) {
	 	this.voucher_date = newVoucher_date;
	} 	  
	/**
	 * 属性dirction的Getter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @return UFBoolean
	 */
	public String getDirction () {
		return dirction;
	}   
	/**
	 * 属性dirction的Setter方法.
	 * 创建日期:2019-03-01 09:24:22
	 * @param newDirction UFBoolean
	 */
	public void setDirction (String newDirction ) {
	 	this.dirction = newDirction;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2019-03-01 09:24:22
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2019-03-01 09:24:22
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_check_balance";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2019-03-01 09:24:22
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "HFM_GL_CHECK_BALANCE";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2019-03-01 09:24:22
	  */
     public CheckBalanceVO() {
		super();	
	}    
} 
