/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.gs.vo;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * 凭证分录VO
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2019-02-14 14:39:03
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class DetailVO extends SuperVO {
	private String pk_corp;
	private UFDateTime ts;
	private UFDate signdatev;
	private UFDouble localdebitamount;
	private String yearv;
	private UFDate checkdate;
	private String free7;
	private String direction;
	private String busireconno;
	private String oppositesubj;
	private String pk_otherorgbook;
	private UFDouble debitamount;
	private String free2;
	private String pk_systemv;
	private String free5;
	private String free10;
	private UFDouble localcreditamount;
	private String free6;
	private String pk_sob;
	private String modifyflag;
	private String pk_voucher;
	private String pk_innercorp;
	private String free3;
	private String pk_managerv;
	private String assid;
	private Integer detailindex;
	private String free9;
	private String errmessage;
	private String bankaccount;
	private UFBoolean convertflag;
	private String errmessageh;
	private UFDouble creditquantity;
	private UFDouble excrate2;
	private UFDouble creditamount;
	private Integer nov;
	private String checkno;
	private String pk_glbook;
	private String pk_sourcepk;
	private String pk_currtype;
	private String errmessage2;
	private String free8;
	private String free11;
	private UFDouble excrate1;
	private Integer voucherkindv;
	private UFDouble price;
	private String pk_glorg;
	private String free4;
	private UFDouble debitquantity;
	private UFBoolean discardflagv;
	private UFBoolean isdifflag;
	private String checkstyle;
	private UFDouble fraccreditamount;
	private String pk_accsubj;
	private String pk_othercorp;
	private String explanation;
	private String pk_detail;
	private UFDate prepareddatev;
	private Integer dr;
	private String pk_glorgbook;
	private String periodv;
	private Integer contrastflag;
	private String pk_vouchertypev;
	private String recieptclass;
	private String pk_offerdetail;
	private String free1;
	private UFDouble fracdebitamount;
	private String pk_innersob;

	public static final String PK_CORP = "pk_corp";
	public static final String SIGNDATEV = "signdatev";
	public static final String LOCALDEBITAMOUNT = "localdebitamount";
	public static final String YEARV = "yearv";
	public static final String CHECKDATE = "checkdate";
	public static final String FREE7 = "free7";
	public static final String DIRECTION = "direction";
	public static final String BUSIRECONNO = "busireconno";
	public static final String OPPOSITESUBJ = "oppositesubj";
	public static final String PK_OTHERORGBOOK = "pk_otherorgbook";
	public static final String DEBITAMOUNT = "debitamount";
	public static final String FREE2 = "free2";
	public static final String PK_SYSTEMV = "pk_systemv";
	public static final String FREE5 = "free5";
	public static final String FREE10 = "free10";
	public static final String LOCALCREDITAMOUNT = "localcreditamount";
	public static final String FREE6 = "free6";
	public static final String PK_SOB = "pk_sob";
	public static final String MODIFYFLAG = "modifyflag";
	public static final String PK_VOUCHER = "pk_voucher";
	public static final String PK_INNERCORP = "pk_innercorp";
	public static final String FREE3 = "free3";
	public static final String PK_MANAGERV = "pk_managerv";
	public static final String ASSID = "assid";
	public static final String DETAILINDEX = "detailindex";
	public static final String FREE9 = "free9";
	public static final String ERRMESSAGE = "errmessage";
	public static final String BANKACCOUNT = "bankaccount";
	public static final String CONVERTFLAG = "convertflag";
	public static final String ERRMESSAGEH = "errmessageh";
	public static final String CREDITQUANTITY = "creditquantity";
	public static final String EXCRATE2 = "excrate2";
	public static final String CREDITAMOUNT = "creditamount";
	public static final String NOV = "nov";
	public static final String CHECKNO = "checkno";
	public static final String PK_GLBOOK = "pk_glbook";
	public static final String PK_SOURCEPK = "pk_sourcepk";
	public static final String PK_CURRTYPE = "pk_currtype";
	public static final String ERRMESSAGE2 = "errmessage2";
	public static final String FREE8 = "free8";
	public static final String FREE11 = "free11";
	public static final String EXCRATE1 = "excrate1";
	public static final String VOUCHERKINDV = "voucherkindv";
	public static final String PRICE = "price";
	public static final String PK_GLORG = "pk_glorg";
	public static final String FREE4 = "free4";
	public static final String DEBITQUANTITY = "debitquantity";
	public static final String DISCARDFLAGV = "discardflagv";
	public static final String ISDIFFLAG = "isdifflag";
	public static final String CHECKSTYLE = "checkstyle";
	public static final String FRACCREDITAMOUNT = "fraccreditamount";
	public static final String PK_ACCSUBJ = "pk_accsubj";
	public static final String PK_OTHERCORP = "pk_othercorp";
	public static final String EXPLANATION = "explanation";
	public static final String PK_DETAIL = "pk_detail";
	public static final String PREPAREDDATEV = "prepareddatev";
	public static final String PK_GLORGBOOK = "pk_glorgbook";
	public static final String PERIODV = "periodv";
	public static final String CONTRASTFLAG = "contrastflag";
	public static final String PK_VOUCHERTYPEV = "pk_vouchertypev";
	public static final String RECIEPTCLASS = "recieptclass";
	public static final String PK_OFFERDETAIL = "pk_offerdetail";
	public static final String FREE1 = "free1";
	public static final String FRACDEBITAMOUNT = "fracdebitamount";
	public static final String PK_INNERSOB = "pk_innersob";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性signdatev的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDate
	 */
	public UFDate getSigndatev () {
		return signdatev;
	}   
	/**
	 * 属性signdatev的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newSigndatev UFDate
	 */
	public void setSigndatev (UFDate newSigndatev ) {
	 	this.signdatev = newSigndatev;
	} 	  
	/**
	 * 属性localdebitamount的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public UFDouble getLocaldebitamount () {
		return localdebitamount;
	}   
	/**
	 * 属性localdebitamount的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newLocaldebitamount UFDouble
	 */
	public void setLocaldebitamount (UFDouble newLocaldebitamount ) {
	 	this.localdebitamount = newLocaldebitamount;
	} 	  
	/**
	 * 属性yearv的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getYearv () {
		return yearv;
	}   
	/**
	 * 属性yearv的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newYearv String
	 */
	public void setYearv (String newYearv ) {
	 	this.yearv = newYearv;
	} 	  
	/**
	 * 属性checkdate的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDate
	 */
	public UFDate getCheckdate () {
		return checkdate;
	}   
	/**
	 * 属性checkdate的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newCheckdate UFDate
	 */
	public void setCheckdate (UFDate newCheckdate ) {
	 	this.checkdate = newCheckdate;
	} 	  
	/**
	 * 属性free7的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getFree7 () {
		return free7;
	}   
	/**
	 * 属性free7的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newFree7 String
	 */
	public void setFree7 (String newFree7 ) {
	 	this.free7 = newFree7;
	} 	  
	/**
	 * 属性direction的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFBoolean
	 */
	public String getDirection () {
		return direction;
	}   
	/**
	 * 属性direction的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newDirection UFBoolean
	 */
	public void setDirection (String newDirection ) {
	 	this.direction = newDirection;
	} 	  
	/**
	 * 属性busireconno的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getBusireconno () {
		return busireconno;
	}   
	/**
	 * 属性busireconno的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newBusireconno String
	 */
	public void setBusireconno (String newBusireconno ) {
	 	this.busireconno = newBusireconno;
	} 	  
	/**
	 * 属性oppositesubj的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getOppositesubj () {
		return oppositesubj;
	}   
	/**
	 * 属性oppositesubj的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newOppositesubj String
	 */
	public void setOppositesubj (String newOppositesubj ) {
	 	this.oppositesubj = newOppositesubj;
	} 	  
	/**
	 * 属性pk_otherorgbook的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_otherorgbook () {
		return pk_otherorgbook;
	}   
	/**
	 * 属性pk_otherorgbook的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_otherorgbook String
	 */
	public void setPk_otherorgbook (String newPk_otherorgbook ) {
	 	this.pk_otherorgbook = newPk_otherorgbook;
	} 	  
	/**
	 * 属性debitamount的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public UFDouble getDebitamount () {
		return debitamount;
	}   
	/**
	 * 属性debitamount的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newDebitamount UFDouble
	 */
	public void setDebitamount (UFDouble newDebitamount ) {
	 	this.debitamount = newDebitamount;
	} 	  
	/**
	 * 属性free2的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getFree2 () {
		return free2;
	}   
	/**
	 * 属性free2的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newFree2 String
	 */
	public void setFree2 (String newFree2 ) {
	 	this.free2 = newFree2;
	} 	  
	/**
	 * 属性pk_systemv的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_systemv () {
		return pk_systemv;
	}   
	/**
	 * 属性pk_systemv的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_systemv String
	 */
	public void setPk_systemv (String newPk_systemv ) {
	 	this.pk_systemv = newPk_systemv;
	} 	  
	/**
	 * 属性free5的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getFree5 () {
		return free5;
	}   
	/**
	 * 属性free5的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newFree5 String
	 */
	public void setFree5 (String newFree5 ) {
	 	this.free5 = newFree5;
	} 	  
	/**
	 * 属性free10的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getFree10 () {
		return free10;
	}   
	/**
	 * 属性free10的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newFree10 String
	 */
	public void setFree10 (String newFree10 ) {
	 	this.free10 = newFree10;
	} 	  
	/**
	 * 属性localcreditamount的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public UFDouble getLocalcreditamount () {
		return localcreditamount;
	}   
	/**
	 * 属性localcreditamount的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newLocalcreditamount UFDouble
	 */
	public void setLocalcreditamount (UFDouble newLocalcreditamount ) {
	 	this.localcreditamount = newLocalcreditamount;
	} 	  
	/**
	 * 属性free6的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getFree6 () {
		return free6;
	}   
	/**
	 * 属性free6的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newFree6 String
	 */
	public void setFree6 (String newFree6 ) {
	 	this.free6 = newFree6;
	} 	  
	/**
	 * 属性pk_sob的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_sob () {
		return pk_sob;
	}   
	/**
	 * 属性pk_sob的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_sob String
	 */
	public void setPk_sob (String newPk_sob ) {
	 	this.pk_sob = newPk_sob;
	} 	  
	/**
	 * 属性modifyflag的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getModifyflag () {
		return modifyflag;
	}   
	/**
	 * 属性modifyflag的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newModifyflag String
	 */
	public void setModifyflag (String newModifyflag ) {
	 	this.modifyflag = newModifyflag;
	} 	  
	/**
	 * 属性pk_voucher的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_voucher () {
		return pk_voucher;
	}   
	/**
	 * 属性pk_voucher的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_voucher String
	 */
	public void setPk_voucher (String newPk_voucher ) {
	 	this.pk_voucher = newPk_voucher;
	} 	  
	/**
	 * 属性pk_innercorp的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_innercorp () {
		return pk_innercorp;
	}   
	/**
	 * 属性pk_innercorp的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_innercorp String
	 */
	public void setPk_innercorp (String newPk_innercorp ) {
	 	this.pk_innercorp = newPk_innercorp;
	} 	  
	/**
	 * 属性free3的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getFree3 () {
		return free3;
	}   
	/**
	 * 属性free3的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newFree3 String
	 */
	public void setFree3 (String newFree3 ) {
	 	this.free3 = newFree3;
	} 	  
	/**
	 * 属性pk_managerv的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_managerv () {
		return pk_managerv;
	}   
	/**
	 * 属性pk_managerv的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_managerv String
	 */
	public void setPk_managerv (String newPk_managerv ) {
	 	this.pk_managerv = newPk_managerv;
	} 	  
	/**
	 * 属性assid的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getAssid () {
		return assid;
	}   
	/**
	 * 属性assid的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newAssid String
	 */
	public void setAssid (String newAssid ) {
	 	this.assid = newAssid;
	} 	  
	/**
	 * 属性detailindex的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public Integer getDetailindex () {
		return detailindex;
	}   
	/**
	 * 属性detailindex的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newDetailindex UFDouble
	 */
	public void setDetailindex (Integer newDetailindex ) {
	 	this.detailindex = newDetailindex;
	} 	  
	/**
	 * 属性free9的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getFree9 () {
		return free9;
	}   
	/**
	 * 属性free9的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newFree9 String
	 */
	public void setFree9 (String newFree9 ) {
	 	this.free9 = newFree9;
	} 	  
	/**
	 * 属性errmessage的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getErrmessage () {
		return errmessage;
	}   
	/**
	 * 属性errmessage的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newErrmessage String
	 */
	public void setErrmessage (String newErrmessage ) {
	 	this.errmessage = newErrmessage;
	} 	  
	/**
	 * 属性bankaccount的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getBankaccount () {
		return bankaccount;
	}   
	/**
	 * 属性bankaccount的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newBankaccount String
	 */
	public void setBankaccount (String newBankaccount ) {
	 	this.bankaccount = newBankaccount;
	} 	  
	/**
	 * 属性convertflag的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFBoolean
	 */
	public UFBoolean getConvertflag () {
		return convertflag;
	}   
	/**
	 * 属性convertflag的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newConvertflag UFBoolean
	 */
	public void setConvertflag (UFBoolean newConvertflag ) {
	 	this.convertflag = newConvertflag;
	} 	  
	/**
	 * 属性errmessageh的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getErrmessageh () {
		return errmessageh;
	}   
	/**
	 * 属性errmessageh的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newErrmessageh String
	 */
	public void setErrmessageh (String newErrmessageh ) {
	 	this.errmessageh = newErrmessageh;
	} 	  
	/**
	 * 属性creditquantity的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public UFDouble getCreditquantity () {
		return creditquantity;
	}   
	/**
	 * 属性creditquantity的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newCreditquantity UFDouble
	 */
	public void setCreditquantity (UFDouble newCreditquantity ) {
	 	this.creditquantity = newCreditquantity;
	} 	  
	/**
	 * 属性excrate2的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public UFDouble getExcrate2 () {
		return excrate2;
	}   
	/**
	 * 属性excrate2的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newExcrate2 UFDouble
	 */
	public void setExcrate2 (UFDouble newExcrate2 ) {
	 	this.excrate2 = newExcrate2;
	} 	  
	/**
	 * 属性creditamount的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public UFDouble getCreditamount () {
		return creditamount;
	}   
	/**
	 * 属性creditamount的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newCreditamount UFDouble
	 */
	public void setCreditamount (UFDouble newCreditamount ) {
	 	this.creditamount = newCreditamount;
	} 	  
	/**
	 * 属性nov的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public Integer getNov () {
		return nov;
	}   
	/**
	 * 属性nov的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newNov UFDouble
	 */
	public void setNov (Integer newNov ) {
	 	this.nov = newNov;
	} 	  
	/**
	 * 属性checkno的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getCheckno () {
		return checkno;
	}   
	/**
	 * 属性checkno的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newCheckno String
	 */
	public void setCheckno (String newCheckno ) {
	 	this.checkno = newCheckno;
	} 	  
	/**
	 * 属性pk_glbook的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_glbook () {
		return pk_glbook;
	}   
	/**
	 * 属性pk_glbook的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_glbook String
	 */
	public void setPk_glbook (String newPk_glbook ) {
	 	this.pk_glbook = newPk_glbook;
	} 	  
	/**
	 * 属性pk_sourcepk的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_sourcepk () {
		return pk_sourcepk;
	}   
	/**
	 * 属性pk_sourcepk的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_sourcepk String
	 */
	public void setPk_sourcepk (String newPk_sourcepk ) {
	 	this.pk_sourcepk = newPk_sourcepk;
	} 	  
	/**
	 * 属性pk_currtype的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_currtype () {
		return pk_currtype;
	}   
	/**
	 * 属性pk_currtype的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_currtype String
	 */
	public void setPk_currtype (String newPk_currtype ) {
	 	this.pk_currtype = newPk_currtype;
	} 	  
	/**
	 * 属性errmessage2的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getErrmessage2 () {
		return errmessage2;
	}   
	/**
	 * 属性errmessage2的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newErrmessage2 String
	 */
	public void setErrmessage2 (String newErrmessage2 ) {
	 	this.errmessage2 = newErrmessage2;
	} 	  
	/**
	 * 属性free8的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getFree8 () {
		return free8;
	}   
	/**
	 * 属性free8的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newFree8 String
	 */
	public void setFree8 (String newFree8 ) {
	 	this.free8 = newFree8;
	} 	  
	/**
	 * 属性free11的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getFree11 () {
		return free11;
	}   
	/**
	 * 属性free11的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newFree11 String
	 */
	public void setFree11 (String newFree11 ) {
	 	this.free11 = newFree11;
	} 	  
	/**
	 * 属性excrate1的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public UFDouble getExcrate1 () {
		return excrate1;
	}   
	/**
	 * 属性excrate1的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newExcrate1 UFDouble
	 */
	public void setExcrate1 (UFDouble newExcrate1 ) {
	 	this.excrate1 = newExcrate1;
	} 	  
	/**
	 * 属性voucherkindv的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public Integer getVoucherkindv () {
		return voucherkindv;
	}   
	/**
	 * 属性voucherkindv的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newVoucherkindv UFDouble
	 */
	public void setVoucherkindv (Integer newVoucherkindv ) {
	 	this.voucherkindv = newVoucherkindv;
	} 	  
	/**
	 * 属性price的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public UFDouble getPrice () {
		return price;
	}   
	/**
	 * 属性price的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPrice UFDouble
	 */
	public void setPrice (UFDouble newPrice ) {
	 	this.price = newPrice;
	} 	  
	/**
	 * 属性pk_glorg的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_glorg () {
		return pk_glorg;
	}   
	/**
	 * 属性pk_glorg的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_glorg String
	 */
	public void setPk_glorg (String newPk_glorg ) {
	 	this.pk_glorg = newPk_glorg;
	} 	  
	/**
	 * 属性free4的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getFree4 () {
		return free4;
	}   
	/**
	 * 属性free4的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newFree4 String
	 */
	public void setFree4 (String newFree4 ) {
	 	this.free4 = newFree4;
	} 	  
	/**
	 * 属性debitquantity的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public UFDouble getDebitquantity () {
		return debitquantity;
	}   
	/**
	 * 属性debitquantity的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newDebitquantity UFDouble
	 */
	public void setDebitquantity (UFDouble newDebitquantity ) {
	 	this.debitquantity = newDebitquantity;
	} 	  
	/**
	 * 属性discardflagv的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFBoolean
	 */
	public UFBoolean getDiscardflagv () {
		return discardflagv;
	}   
	/**
	 * 属性discardflagv的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newDiscardflagv UFBoolean
	 */
	public void setDiscardflagv (UFBoolean newDiscardflagv ) {
	 	this.discardflagv = newDiscardflagv;
	} 	  
	/**
	 * 属性isdifflag的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFBoolean
	 */
	public UFBoolean getIsdifflag () {
		return isdifflag;
	}   
	/**
	 * 属性isdifflag的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newIsdifflag UFBoolean
	 */
	public void setIsdifflag (UFBoolean newIsdifflag ) {
	 	this.isdifflag = newIsdifflag;
	} 	  
	/**
	 * 属性checkstyle的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getCheckstyle () {
		return checkstyle;
	}   
	/**
	 * 属性checkstyle的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newCheckstyle String
	 */
	public void setCheckstyle (String newCheckstyle ) {
	 	this.checkstyle = newCheckstyle;
	} 	  
	/**
	 * 属性fraccreditamount的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public UFDouble getFraccreditamount () {
		return fraccreditamount;
	}   
	/**
	 * 属性fraccreditamount的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newFraccreditamount UFDouble
	 */
	public void setFraccreditamount (UFDouble newFraccreditamount ) {
	 	this.fraccreditamount = newFraccreditamount;
	} 	  
	/**
	 * 属性pk_accsubj的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_accsubj () {
		return pk_accsubj;
	}   
	/**
	 * 属性pk_accsubj的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_accsubj String
	 */
	public void setPk_accsubj (String newPk_accsubj ) {
	 	this.pk_accsubj = newPk_accsubj;
	} 	  
	/**
	 * 属性pk_othercorp的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_othercorp () {
		return pk_othercorp;
	}   
	/**
	 * 属性pk_othercorp的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_othercorp String
	 */
	public void setPk_othercorp (String newPk_othercorp ) {
	 	this.pk_othercorp = newPk_othercorp;
	} 	  
	/**
	 * 属性explanation的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getExplanation () {
		return explanation;
	}   
	/**
	 * 属性explanation的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newExplanation String
	 */
	public void setExplanation (String newExplanation ) {
	 	this.explanation = newExplanation;
	} 	  
	/**
	 * 属性pk_detail的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_detail () {
		return pk_detail;
	}   
	/**
	 * 属性pk_detail的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_detail String
	 */
	public void setPk_detail (String newPk_detail ) {
	 	this.pk_detail = newPk_detail;
	} 	  
	/**
	 * 属性prepareddatev的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDate
	 */
	public UFDate getPrepareddatev () {
		return prepareddatev;
	}   
	/**
	 * 属性prepareddatev的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPrepareddatev UFDate
	 */
	public void setPrepareddatev (UFDate newPrepareddatev ) {
	 	this.prepareddatev = newPrepareddatev;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性pk_glorgbook的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_glorgbook () {
		return pk_glorgbook;
	}   
	/**
	 * 属性pk_glorgbook的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_glorgbook String
	 */
	public void setPk_glorgbook (String newPk_glorgbook ) {
	 	this.pk_glorgbook = newPk_glorgbook;
	} 	  
	/**
	 * 属性periodv的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPeriodv () {
		return periodv;
	}   
	/**
	 * 属性periodv的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPeriodv String
	 */
	public void setPeriodv (String newPeriodv ) {
	 	this.periodv = newPeriodv;
	} 	  
	/**
	 * 属性contrastflag的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public Integer getContrastflag () {
		return contrastflag;
	}   
	/**
	 * 属性contrastflag的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newContrastflag UFDouble
	 */
	public void setContrastflag (Integer newContrastflag ) {
	 	this.contrastflag = newContrastflag;
	} 	  
	/**
	 * 属性pk_vouchertypev的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_vouchertypev () {
		return pk_vouchertypev;
	}   
	/**
	 * 属性pk_vouchertypev的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_vouchertypev String
	 */
	public void setPk_vouchertypev (String newPk_vouchertypev ) {
	 	this.pk_vouchertypev = newPk_vouchertypev;
	} 	  
	/**
	 * 属性recieptclass的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getRecieptclass () {
		return recieptclass;
	}   
	/**
	 * 属性recieptclass的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newRecieptclass String
	 */
	public void setRecieptclass (String newRecieptclass ) {
	 	this.recieptclass = newRecieptclass;
	} 	  
	/**
	 * 属性pk_offerdetail的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_offerdetail () {
		return pk_offerdetail;
	}   
	/**
	 * 属性pk_offerdetail的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_offerdetail String
	 */
	public void setPk_offerdetail (String newPk_offerdetail ) {
	 	this.pk_offerdetail = newPk_offerdetail;
	} 	  
	/**
	 * 属性free1的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getFree1 () {
		return free1;
	}   
	/**
	 * 属性free1的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newFree1 String
	 */
	public void setFree1 (String newFree1 ) {
	 	this.free1 = newFree1;
	} 	  
	/**
	 * 属性fracdebitamount的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return UFDouble
	 */
	public UFDouble getFracdebitamount () {
		return fracdebitamount;
	}   
	/**
	 * 属性fracdebitamount的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newFracdebitamount UFDouble
	 */
	public void setFracdebitamount (UFDouble newFracdebitamount ) {
	 	this.fracdebitamount = newFracdebitamount;
	} 	  
	/**
	 * 属性pk_innersob的Getter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @return String
	 */
	public String getPk_innersob () {
		return pk_innersob;
	}   
	/**
	 * 属性pk_innersob的Setter方法.
	 * 创建日期:2019-02-14 14:39:03
	 * @param newPk_innersob String
	 */
	public void setPk_innersob (String newPk_innersob ) {
	 	this.pk_innersob = newPk_innersob;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2019-02-14 14:39:03
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2019-02-14 14:39:03
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_detail";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2019-02-14 14:39:03
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "GL_DETAIL";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2019-02-14 14:39:03
	  */
     public DetailVO() {
		super();	
	}    
} 
