/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.gs.vo;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2019-01-24 15:30:24
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class VoucherRecordVO extends SuperVO {
	private String pk_corp;//公司编码

	private UFDouble local_credit_currency;//本币贷方
	private UFDouble local_debtor_currency;//本币借方
	private UFDouble original_credit_currency;//原币贷方
	private UFDouble original_debtor_currency;//原币借方
	private String pk_vocher;//凭证主键
	private String pk_vouchertypev;//凭证类别
	private String pk_system;//来源系统
	private Integer scbz;//生成凭证标志  0为过账成功 1为过账失败 为空即未过账
	private String pk_glbook;//账簿
	private String pk_glorgbook;//主体账簿
	private String pk_glorg;//主体
	private Integer fjzs;//附件张数
	private String def1;//核算项
	private String def2;
	private String def3;
	private String def4;
	private String def5;
	private String def6;
	private String def7;
	private String def8;
	private String def9;
	private String def11;//失败原因
	private String pk_currtype;//币种
	private String pk_voucher_record;//主键
	private String vapproveid;//审核人
	private String vapprovedate;//审核日期
	private String makedate;//制单日期
	private String abs_summary;//摘要
	private String subjcode;//科目编码
	private Integer detailindex;//凭证分录号
	private String voperatorid;//制单人
	private String pk_detail;//凭证分录主键
	private Integer dr;
	private UFDateTime ts;
	//资金添加
	private Integer hfm_voucher_interface_id;//资金接口表ID
	private String hfm_group_batch_id;//资金同一组分录批次号
	private String hfm_transaction_number;//资金事务编号
	private String hfm_transfer_batch_id;//资金传送批次号

	
	public static final String HFM_VOUCHER_INTERFACE_ID="hfm_voucher_interface_id";
	public static final String HFM_GROUP_BATCH_ID="hfm_group_batch_id";
	public static final String HFM_TRANSACTION_NUMBER="hfm_transaction_number";
	public static final String HFM_TRANSFER_BATCH_ID="hfm_transfer_batch_id";
	//资金添加 end 
	public static final String PK_CORP = "pk_corp";
	public static final String LOCAL_CREDIT_CURRENCY = "local_credit_currency";
	public static final String DEF7 = "def7";
	public static final String PK_GLBOOK = "pk_glbook";
	public static final String DEF8 = "def8";
	public static final String PK_CURRTYPE = "pk_currtype";
	public static final String LOCAL_DEBTOR_CURRENCY = "local_debtor_currency";
	public static final String PK_VOUCHER_RECORD = "pk_voucher_record";
	public static final String DEF5 = "def5";
	public static final String ORIGINAL_CREDIT_CURRENCY = "original_credit_currency";
	public static final String VAPPROVEID = "vapproveid";
	public static final String PK_VOCHER = "pk_vocher";
	public static final String DEF9 = "def9";
	public static final String DEF6 = "def6";
	public static final String DEF11 = "def11";
	public static final String PK_GLORG = "pk_glorg";
	public static final String DEF3 = "def3";
	public static final String PK_SYSTEM = "pk_system";
	public static final String SCBZ = "scbz";
	public static final String DEF2 = "def2";
	public static final String MAKEDATE = "makedate";
	public static final String DEF1 = "def1";
	public static final String ORIGINAL_DEBTOR_CURRENCY = "original_debtor_currency";
	public static final String ABS_SUMMARY = "abs_summary";
	public static final String SUBJCODE = "subjcode";
	public static final String DETAILINDEX = "detailindex";
	public static final String VOPERATORID = "voperatorid";
	public static final String PK_DETAIL = "pk_detail";
	public static final String DEF4 = "def4";
	public static final String PK_GLORGBOOK = "pk_glorgbook";
	public static final String FJZS = "fjzs";
	public static final String PK_VOUCHERTYPEV = "pk_vouchertypev";
			
	
	public Integer getHfm_voucher_interface_id() {
		return hfm_voucher_interface_id;
	}
	public void setHfm_voucher_interface_id(Integer hfm_voucher_interface_id) {
		this.hfm_voucher_interface_id = hfm_voucher_interface_id;
	}
	public String getHfm_group_batch_id() {
		return hfm_group_batch_id;
	}
	public void setHfm_group_batch_id(String hfm_group_batch_id) {
		this.hfm_group_batch_id = hfm_group_batch_id;
	}
	public String getHfm_transaction_number() {
		return hfm_transaction_number;
	}
	public void setHfm_transaction_number(String hfm_transaction_number) {
		this.hfm_transaction_number = hfm_transaction_number;
	}
	public String getHfm_transfer_batch_id() {
		return hfm_transfer_batch_id;
	}
	public void setHfm_transfer_batch_id(String hfm_transfer_batch_id) {
		this.hfm_transfer_batch_id = hfm_transfer_batch_id;
	}
	public String getVapprovedate() {
		return vapprovedate;
	}
	public void setVapprovedate(String vapprovedate) {
		this.vapprovedate = vapprovedate;
	}
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性local_credit_currency的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return UFDouble
	 */
	public UFDouble getLocal_credit_currency () {
		return local_credit_currency;
	}   
	/**
	 * 属性local_credit_currency的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newLocal_credit_currency UFDouble
	 */
	public void setLocal_credit_currency (UFDouble newLocal_credit_currency ) {
	 	this.local_credit_currency = newLocal_credit_currency;
	} 	  
	/**
	 * 属性def7的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getDef7 () {
		return def7;
	}   
	/**
	 * 属性def7的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newDef7 String
	 */
	public void setDef7 (String newDef7 ) {
	 	this.def7 = newDef7;
	} 	  
	/**
	 * 属性pk_glbook的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getPk_glbook () {
		return pk_glbook;
	}   
	/**
	 * 属性pk_glbook的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newPk_glbook String
	 */
	public void setPk_glbook (String newPk_glbook ) {
	 	this.pk_glbook = newPk_glbook;
	} 	  
	/**
	 * 属性def8的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getDef8 () {
		return def8;
	}   
	/**
	 * 属性def8的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newDef8 String
	 */
	public void setDef8 (String newDef8 ) {
	 	this.def8 = newDef8;
	} 	  
	/**
	 * 属性pk_currtype的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getPk_currtype () {
		return pk_currtype;
	}   
	/**
	 * 属性pk_currtype的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newPk_currtype String
	 */
	public void setPk_currtype (String newPk_currtype ) {
	 	this.pk_currtype = newPk_currtype;
	} 	  
	/**
	 * 属性local_debtor_currency的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return UFDouble
	 */
	public UFDouble getLocal_debtor_currency () {
		return local_debtor_currency;
	}   
	/**
	 * 属性local_debtor_currency的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newLocal_debtor_currency UFDouble
	 */
	public void setLocal_debtor_currency (UFDouble newLocal_debtor_currency ) {
	 	this.local_debtor_currency = newLocal_debtor_currency;
	} 	  
	/**
	 * 属性pk_voucher_record的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getPk_voucher_record () {
		return pk_voucher_record;
	}   
	/**
	 * 属性pk_voucher_record的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newPk_voucher_record String
	 */
	public void setPk_voucher_record (String newPk_voucher_record ) {
	 	this.pk_voucher_record = newPk_voucher_record;
	} 	  
	/**
	 * 属性def5的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getDef5 () {
		return def5;
	}   
	/**
	 * 属性def5的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newDef5 String
	 */
	public void setDef5 (String newDef5 ) {
	 	this.def5 = newDef5;
	} 	  
	/**
	 * 属性original_credit_currency的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return UFDouble
	 */
	public UFDouble getOriginal_credit_currency () {
		return original_credit_currency;
	}   
	/**
	 * 属性original_credit_currency的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newOriginal_credit_currency UFDouble
	 */
	public void setOriginal_credit_currency (UFDouble newOriginal_credit_currency ) {
	 	this.original_credit_currency = newOriginal_credit_currency;
	} 	  
	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getVapproveid () {
		return vapproveid;
	}   
	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newVapproveid String
	 */
	public void setVapproveid (String newVapproveid ) {
	 	this.vapproveid = newVapproveid;
	} 	  
	/**
	 * 属性pk_vocher的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getPk_vocher () {
		return pk_vocher;
	}   
	/**
	 * 属性pk_vocher的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newPk_vocher String
	 */
	public void setPk_vocher (String newPk_vocher ) {
	 	this.pk_vocher = newPk_vocher;
	} 	  
	/**
	 * 属性def9的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getDef9 () {
		return def9;
	}   
	/**
	 * 属性def9的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newDef9 String
	 */
	public void setDef9 (String newDef9 ) {
	 	this.def9 = newDef9;
	} 	  
	/**
	 * 属性def6的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getDef6 () {
		return def6;
	}   
	/**
	 * 属性def6的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newDef6 String
	 */
	public void setDef6 (String newDef6 ) {
	 	this.def6 = newDef6;
	} 	  
	/**
	 * 属性def11的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getDef11 () {
		return def11;
	}   
	/**
	 * 属性def11的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newDef11 String
	 */
	public void setDef11 (String newDef11 ) {
	 	this.def11 = newDef11;
	} 	  
	/**
	 * 属性pk_glorg的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getPk_glorg () {
		return pk_glorg;
	}   
	/**
	 * 属性pk_glorg的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newPk_glorg String
	 */
	public void setPk_glorg (String newPk_glorg ) {
	 	this.pk_glorg = newPk_glorg;
	} 	  
	/**
	 * 属性def3的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getDef3 () {
		return def3;
	}   
	/**
	 * 属性def3的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newDef3 String
	 */
	public void setDef3 (String newDef3 ) {
	 	this.def3 = newDef3;
	} 	  
	/**
	 * 属性pk_system的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getPk_system () {
		return pk_system;
	}   
	/**
	 * 属性pk_system的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newPk_system String
	 */
	public void setPk_system (String newPk_system ) {
	 	this.pk_system = newPk_system;
	} 	  
	/**
	 * 属性scbz的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return UFDouble
	 */
	public Integer getScbz () {
		return scbz;
	}   
	/**
	 * 属性scbz的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newScbz UFDouble
	 */
	public void setScbz (Integer newScbz ) {
	 	this.scbz = newScbz;
	} 	  
	/**
	 * 属性def2的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getDef2 () {
		return def2;
	}   
	/**
	 * 属性def2的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newDef2 String
	 */
	public void setDef2 (String newDef2 ) {
	 	this.def2 = newDef2;
	} 	  
	/**
	 * 属性makedate的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return UFDateTime
	 */
	public String getMakedate () {
		return makedate;
	}   
	/**
	 * 属性makedate的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newMakedate UFDateTime
	 */
	public void setMakedate (String newMakedate ) {
	 	this.makedate = newMakedate;
	} 	  
	/**
	 * 属性def1的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getDef1 () {
		return def1;
	}   
	/**
	 * 属性def1的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newDef1 String
	 */
	public void setDef1 (String newDef1 ) {
	 	this.def1 = newDef1;
	} 	  
	/**
	 * 属性original_debtor_currency的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return UFDouble
	 */
	public UFDouble getOriginal_debtor_currency () {
		return original_debtor_currency;
	}   
	/**
	 * 属性original_debtor_currency的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newOriginal_debtor_currency UFDouble
	 */
	public void setOriginal_debtor_currency (UFDouble newOriginal_debtor_currency ) {
	 	this.original_debtor_currency = newOriginal_debtor_currency;
	} 	  
	/**
	 * 属性abs_summary的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getAbs_summary () {
		return abs_summary;
	}   
	/**
	 * 属性abs_summary的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newAbs_summary String
	 */
	public void setAbs_summary (String newAbs_summary ) {
	 	this.abs_summary = newAbs_summary;
	} 	  
	/**
	 * 属性subjcode的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getSubjcode () {
		return subjcode;
	}   
	/**
	 * 属性subjcode的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newSubjcode String
	 */
	public void setSubjcode (String newSubjcode ) {
	 	this.subjcode = newSubjcode;
	} 	  
	/**
	 * 属性detailindex的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return UFDouble
	 */
	public Integer getDetailindex () {
		return detailindex;
	}   
	/**
	 * 属性detailindex的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newDetailindex UFDouble
	 */
	public void setDetailindex (Integer newDetailindex ) {
	 	this.detailindex = newDetailindex;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
	 	this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性pk_detail的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getPk_detail () {
		return pk_detail;
	}   
	/**
	 * 属性pk_detail的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newPk_detail String
	 */
	public void setPk_detail (String newPk_detail ) {
	 	this.pk_detail = newPk_detail;
	} 	  
	/**
	 * 属性def4的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getDef4 () {
		return def4;
	}   
	/**
	 * 属性def4的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newDef4 String
	 */
	public void setDef4 (String newDef4 ) {
	 	this.def4 = newDef4;
	} 	  
	/**
	 * 属性pk_glorgbook的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getPk_glorgbook () {
		return pk_glorgbook;
	}   
	/**
	 * 属性pk_glorgbook的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newPk_glorgbook String
	 */
	public void setPk_glorgbook (String newPk_glorgbook ) {
	 	this.pk_glorgbook = newPk_glorgbook;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性fjzs的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return UFDouble
	 */
	public Integer getFjzs () {
		return fjzs;
	}   
	/**
	 * 属性fjzs的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newFjzs UFDouble
	 */
	public void setFjzs (Integer newFjzs ) {
	 	this.fjzs = newFjzs;
	} 	  
	/**
	 * 属性pk_vouchertypev的Getter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @return String
	 */
	public String getPk_vouchertypev () {
		return pk_vouchertypev;
	}   
	/**
	 * 属性pk_vouchertypev的Setter方法.
	 * 创建日期:2019-01-24 15:30:24
	 * @param newPk_vouchertypev String
	 */
	public void setPk_vouchertypev (String newPk_vouchertypev ) {
	 	this.pk_vouchertypev = newPk_vouchertypev;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2019-01-24 15:30:24
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2019-01-24 15:30:24
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_voucher_record";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2019-01-24 15:30:24
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "GS_VOUCHER_RECORD";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2019-01-24 15:30:24
	  */
     public VoucherRecordVO() {
		super();	
	}
   
     
} 
